canonical/sdcore-upf-operator

- config.yaml
- requirements.in
- requirements.txt
- src/charm.py
- src/machine.py
- src/templates/upf.json.j2
- tests/unit/expected_upf.json
- tests/unit/test_charm.py
Add the UPF configuration file generation using Jinja template. We also introduce the `machine` abstraction that is responsible for handling everything machine related using the same API as `ops.pebble`.
- Currently some values used in the config file are hardcoded (ex. DNN, upf mode, etc.). Those will get configurable through future PR's.
> feat: Add upf config file generation

- README.md
- src/charm.py
- src/machine.py
- tests/unit/test_charm.py
Start UPF service using the `sdcore-upf` snap daemons. This includes extending the `Machine` with `exec` .
- This PR depends on the `sdcore-upf.bessctl` cli app implemented here: https://github.com/canonical/sdcore-upf-snap/pull/5
> feat: start upf service

- src/charm.py
- tests/unit/test_charm.py
Stop upf service and remove upf snap on charm removal.
Fixes #13
> feat: remove upf snap on charm removal

- .github/workflows/integration-tests.yaml
- .github/workflows/main.yaml
- .github/workflows/resources/upf-local-cloud.yaml
- tests/integration/test_charm.py
- Changes the environment for the integration tests
- PS5-based self-hosted runners have been added to the project
- New integration workflow will create a Multipass VM on the self-hosted runner and use it for deploying the UPF machine charm
- Adds some basic integration tests for the machine charm
> chore: UPF machine charm integration tests

- .github/workflows/integration-tests.yaml
- src/charm.py
This PR aims to fix #34 by increasing the `timeout` parameter for command execution in the gRPC readiness check method.
> fix: Increase timeout for bessctl command in gRPC readiness check

- src/charm.py
- tests/unit/test_charm.py
This PR aims to fix #29, by checking that services exist before stopping them.
> fix: stop services on removal only if they exist

- .github/dependabot.yml
This PR aims to block dependabot to try to bump the major version of pydantic.
> chore: ignore major updates for pydantic

- tox.ini
This PR aims to fix #41. It instructs `pytest-operator` to run on the already existing `upf-integration` juju model, so `juju-crashdump` will collect logs from the correct model (only on failure).
> fix: run integration tests on static juju model

- .github/workflows/main.yaml
- .github/workflows/promote.yaml
- README.md
- src/charm.py
- tests/unit/test_charm.py
Bump workload to v1.4.0 and publish charm to `1.4/edge` on Charmhub.
The charmhub `1.4` track was requested and created:
- https://discourse.charmhub.io/t/create-a-1-4-track-for-sd-core-charms/13790/2
> chore: bump to v1.4.0

- pyproject.toml
- tests/integration/test_integration.py
- tests/unit/test_charm.py
- tests/unit/test_upf_network.py
Enable line length check (E501) in ruff
> chore: enable ruff line length check

- src/charm.py
- tests/unit/test_charm.py
As of https://github.com/canonical/sdcore-upf-snap/pull/19, a newer version and track are to be used. This updates the charm to use the correct track for the snap.
N/A I have made corresponding changes to the documentation
> chore: update to use 1.4 track

- src/charm.py
- tests/unit/test_charm.py
Start each service in order, and configure bess before routectl starts up. This should prevent the hanging in the `up4.bess` script
- N/A Any dependent changes have been merged and published in downstream modules
- N/A I have bumped the version of the library
> fix: Control startup order

- src/charm.py
- tests/unit/test_charm.py
This PR aims to add CPU validation for the UPF machine charm. If the CPU does not support `avx2` and `rdrand` instructions, charm will go into blocked status.
> feat: add CPU validation

- tests/unit/test_charm.py
- tests/unit/test_upf_network.py
This PR aims to remove `unittest` framework in favor of `pytest`, as described [here](https://juju.is/docs/sdk/write-a-unit-test-for-a-charm).
Main changes:
* Use fixtures to configure patches
> chore: use pytest for unit tests

- src/charm.py
- src/upf_network.py
- tests/unit/test_charm.py
- tests/unit/test_upf_network.py
This PR aims to fix #75.
Main changes:
* log route creation error instead of raising an exception (this avoids the `hook-failed`)
* early stop charm configuration if the full networking is not properly configured (addresses and routes)
> fix: log route creation error and early stop configuration

- terraform/main.tf
When trying the documentation in https://github.com/canonical/charmed-aether-sd-core/pull/17, I encountered the error:
```
juju_application.upf: Creating...
╷
│ Error: Client Error
│ 
│   with juju_application.upf,
│   on main.tf line 4, in resource "juju_application" "upf":
│    4: resource "juju_application" "upf" {
│ 
│ Unable to create application, got error: base from placements, "amd64/ubuntu/22.04/stable", does not match requested base "amd64"
```
After some research in issues related to placement with the juju provider, I tried adding the base in the module, and it fixed the error.
> fix: Add base to terraform module to prevent placement error

- src/upf_network.py
- tests/unit/test_upf_network.py
Fixes the `Network is unreachable` problem which is described below by making the interfaces up after UPF network configuration.
```
Env is an EC2 instance. Two additional interfaces attached for access and core.
Configuration passed to the charm included interface name, interface IP and gateway IP.
Network interfaces are configured correctly, but both are `DOWN`. 
Charm code should make sure that the interfaces have been brought UP after changing configuration.
```
> fix: make the interfaces up after configuration

- .github/workflows/integration-tests.yaml
- .github/workflows/main.yaml
- charmcraft.yaml
- src/charm.py
- src/charm_config.py
- src/upf_network.py
- tests/integration/test_integration.py
- tests/unit/test_charm.py
- tests/unit/test_upf_network.py
This PR implements DPDK support in the machine charm.
DPDK mode can be enabled through the new charm config param - `upf-mode`. Using DPDK also requires supplying two additional parameters for each of the `access` and `core` interfaces - the MAC address and the device's PCI address.
DPDK requires HugePages to be available on the host machine (at least 2x1G). A driver for the `access` and `core` network interfaces should also be changed to `vfio-pci`. Both these requirements need to be ensured manually before deploying the charm.
NOTE:
In some environments Ubuntu 24.04 will be required to run UPF in DPDK mode, hence the base for the charm has been updated. GitHub workflow for building the charm has been changed to allow using the latest base. Once support for latest base lands in a stable …
> feat: Adds DPDK support

- terraform/README.md
- terraform/main.tf
- terraform/variables.tf
Adds possibility of specifying the base of the charm in the Terraform module. The default base is set to `ubuntu@24.04` because latest builds are targeted for this base.
> chore: Adds possibility of specifying the base of the charm in the Terraform module

- tests/unit/fixtures.py
- tests/unit/test_charm_collect_status.py
- tests/unit/test_charm_configure.py
- tests/unit/test_charm_remove.py
Now that scenario testing is built into ops we use ops.testing instead of directly calling scenario. Both have the same API. scenario still needs to be independently installed.
> chore: use built-in testing from ops

- src/charm.py
This PR aims to fix an issue for which metrics provided by UPF could not be seen in COS Dashboard.
> fix: use correct parameters to export UPF metrics
